language: groovy
jdk:
  - oraclejdk7
env:
  - GRAILS_VERSION=2.5.0
  - GRAILS_VERSION=2.4.5
  - GRAILS_VERSION=2.4.4
  - GRAILS_VERSION=2.4.3
  - GRAILS_VERSION=2.4.2
  - GRAILS_VERSION=2.4.1
  - GRAILS_VERSION=2.4.0
  - GRAILS_VERSION=2.3.11
  - GRAILS_VERSION=2.3.5
  - GRAILS_VERSION=2.3.0
before_install:
- rm -rf ~/.sdkman
- curl -s http://get.sdkman.io > ~/install_sdkman.sh
- chmod 775 ~/install_sdkman.sh
- ~/install_sdkman.sh
- echo "sdkman_auto_answer=true" > ~/.sdkman/etc/config
- source ~/.sdkman/bin/sdkman-init.sh
- sdk install grails $GRAILS_VERSION || true
matrix:
  allow_failures:
    - env: GRAILS_VERSION=2.3.11
    - env: GRAILS_VERSION=2.3.5
    - env: GRAILS_VERSION=2.3.0
branches:
  except:
    - gh-pages
script: grails clean &&
  [[ $GRAILS_VERSION =~ ([1-2]\.[0-3]\.[0-9]) ]] && grails upgrade --non-interactive || grails set-grails-version $GRAILS_VERSION --non-interactive
  && grails test-app -coverage -xml --non-interactive
after_success:
  grails coveralls
